
name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Docker Login
     
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets:DOCKERHUB_USER }}
          password: ${{ secrets:DOCKERHUB_PWD }}
          

      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
